# Generated by Django 3.1.5 on 2021-01-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_auto_20210120_1044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='parameters',
            new_name='parameter',
        ),
        migrations.RemoveField(
            model_name='data',
            name='data',
        ),
        migrations.AddField(
            model_name='data',
            name='data_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.ImageField(upload_to='results'),
        ),
    ]
