# Generated by Django 3.1.5 on 2021-01-20 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_auto_20210120_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='data_url',
            new_name='dataset_url',
        ),
    ]
