# Generated by Django 3.1.5 on 2021-01-20 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_result'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parameters',
            new_name='Parameter',
        ),
    ]
